import { IoEllipsisHorizontal, IoCheckmarkCircle, IoLocation, IoDiamond, IoInfinite, IoPrism, IoStorefront, IoBug, IoEarth, IoInformationCircle, IoConstruct, IoExtensionPuzzle, IoEye, IoFlame, IoFish, IoHourglass, IoMedal, IoPlanet, IoRocket, IoTrophy, IoWarning, IoWater, IoRibbon, IoPeopleCircle, IoPeopleCircleOutline, IoHammer, IoHammerOutline, IoAnalyticsOutline, IoBulbOutline, IoBuildOutline, IoStarOutline, IoEgg } from 'react-icons/io5';

export const icons = {
    "ellipsis-horizontal": <IoEllipsisHorizontal />,
    "checkmark-circle": <IoCheckmarkCircle />,
    "location": <IoLocation />,
    "diamond": <IoDiamond />,
    "infinite": <IoInfinite />,
    "prism": <IoPrism />,
    "storefront": <IoStorefront />,
    "bug": <IoBug />,
    "earth": <IoEarth />,
    "info": <IoInformationCircle />,
    "construct": <IoConstruct />,
    "puzzle": <IoExtensionPuzzle />,
    "eye": <IoEye />,
    "flame": <IoFlame />,
    "fish": <IoFish />,
    "hourglass": <IoHourglass />,
    "medal": <IoMedal />,
    "planet": <IoPlanet />,
    "ribbon": <IoRibbon />,
    "rocket": <IoRocket />,
    "trophy": <IoTrophy />,
    "warning": <IoWarning />,
    "water": <IoWater />,
    "people-circle-outline": <IoPeopleCircleOutline />,
    "hammer-outline": <IoHammerOutline />,
    "analytics-outline": <IoAnalyticsOutline />,
    "bulb-outline": <IoBulbOutline />,
    "build-outline": <IoBuildOutline />,
    "star-outline": <IoStarOutline />,
    "egg": <IoEgg />,
    "checkmark": <IoCheckmarkCircle />
}